outputs:
  output-path:
    value: hidpi/build

runs:
  using: composite

  steps:
  - name: Install dependencies
    run: |
      sudo apt update
      sudo apt install inkscape optipng
    shell: bash

  - name: Build themes
    working-directory: hidpi
    run: ./build.sh
    shell: bash
