name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - id: do-build
      name: Run .github/actions/do-build
      uses: ./.github/actions/do-build

    - uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.do-build.outputs.output-path }}
        if-no-files-found: error
